// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Alfred Jean LLC

//! Centralized environment variable definitions and accessors for wokd.
//!
//! All runtime env vars are defined here. Constants are generated by `build.rs`.

use std::path::PathBuf;

/// Generated env var name constants.
// KEEP UNTIL: RUST_LOG is referenced in code (currently read by tracing-subscriber directly)
#[allow(dead_code)]
mod names {
    include!(concat!(env!("OUT_DIR"), "/env_names.rs"));
}

/// Returns the value of `WOK_STATE_DIR` as a `PathBuf`, if set.
///
/// When set, this overrides the default state directory location.
pub fn state_dir() -> Option<PathBuf> {
    std::env::var(names::WOK_STATE_DIR).ok().map(PathBuf::from)
}

/// Returns the value of `XDG_STATE_HOME` as a `PathBuf`, if set.
///
/// Used as a fallback when `WOK_STATE_DIR` is not set.
/// The wok state directory is `$XDG_STATE_HOME/wok`.
pub fn xdg_state_home() -> Option<PathBuf> {
    std::env::var(names::XDG_STATE_HOME).ok().map(PathBuf::from)
}

#[cfg(test)]
#[path = "env_tests.rs"]
mod tests;
